/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib.Algebra.Group.Pointwise.Finset.Basic
import Mathlib.Analysis.Complex.Exponential
import Mathlib.Analysis.SpecialFunctions.Complex.Log
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Complex
import Mathlib.CategoryTheory.Category.Basic
import Mathlib.Data.Finset.Sort
import Mathlib.Data.Nat.Basic
import Mathlib.Data.Nat.Nth
import Mathlib.Data.Nat.Prime.Basic
import Mathlib.Data.Real.Basic
import Mathlib.Data.ZMod.QuotientRing
import Mathlib.NumberTheory.ArithmeticFunction.Defs
import Mathlib.NumberTheory.Bertrand
import Mathlib.NumberTheory.PrimeCounting
import Mathlib.Tactic.Cases
import Mathlib.Tactic.Check
import Mathlib.Tactic.Common
import Mathlib.Tactic.Constructor
import Mathlib.Tactic.Eval
import Mathlib.Tactic.Ext
import Mathlib.Tactic.Generalize
import Mathlib.Tactic.HaveI
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.NormNum.LegendreSymbol
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.RealSqrt
import Mathlib.Tactic.Positivity
import Mathlib.Tactic.Push
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Ring.RingNF
import Mathlib.Tactic.SimpRw
import Mathlib.Tactic.SplitIfs
import Mathlib.Tactic.Tauto
import Mathlib.Tactic.Trace
import Mathlib.Tactic.TypeStar
import Mathlib.Tactic.Use
import Mathlib.Tactic.Variable


/-!
# Core Definitions for the Krafft Sieve

This module establishes the foundational definitions for the sieve:
- $\mathcal{P}_n$: The target set of primes.
- $q$: The primorial $q = \prod_{p \in \mathcal{P}_n} p$.
- $\mathcal{A}_n$: The target interval.
- $g_i, c$: Local and global hit counters.
- $S_1, S_2$: Weighted sums over the interval.
-/

namespace KrafftSieve

open scoped BigOperators Real Nat Pointwise

noncomputable section

/-- Definition of the set of primes P_n.
Let $\mathcal{P}_n$ denote the set of primes $p$ such that $5 \le p < 6n+2$. -/
def P_n (n : ℕ) : Finset ℕ :=
  (Finset.range (6 * n + 2)).filter (fun p => 5 ≤ p ∧ p.Prime)

/-- Definition of the primorial q.
Define the primorial $q = \prod_{p \in \mathcal{P}_n} p$. -/
def q (n : ℕ) : ℕ := (P_n n).prod (fun p => p)

/-- Definition of w as the cardinality of P_n.
Let $w = |\mathcal{P}_n|$ be the number of distinct prime factors of $q$. -/
def w (n : ℕ) : ℕ := (P_n n).card

/-- Definition of the sorted list of primes and the accessor function p_i.
Index the primes in $\mathcal{P}_n$ as $p_1, p_2, \dots, p_w$. -/
def primes_list (n : ℕ) : List ℕ := (P_n n).sort (· ≤ ·)

/-- Access the $i$-th prime $p_i$. Note that we use 0-based indexing for the implementation,
so $p_0$ corresponds to the user's $p_1$. -/
def p (n : ℕ) (i : Fin (w n)) : ℕ := (primes_list n).get (i.cast (by
  unfold w primes_list
  simp_all only [Finset.length_sort]))

/-- Define r^K
Define the Krafft tuple r^K such that for each 1 <= i <= w,
r^K_i = floor((p_i+1)/6). -/
def r_K (n : ℕ) (i : Fin (w n)) : ℕ := (p n i + 1) / 6

/-- Define A_n
Define the target interval of indices:
A_n = {x in N | 6n^2 - 2n <= x <= 6n^2 + 10n + 3}. -/
def A_n (n : ℕ) : Finset ℕ :=
  Finset.Icc (6 * n ^ 2 - 2 * n) (6 * n ^ 2 + 10 * n + 3)

/-- Define the local hit function g_i(x)
Define the local hit function $g_i : \mathbb{Z}/q\mathbb{Z} \to \mathbb{R}$
for each prime index $i \in \{1, \dots, w\}$.
- $g_i(x) = 1$ if $x \equiv r^K_i \pmod{p_i}$ or $x \equiv -r^K_i \pmod{p_i}$.
- Otherwise, $g_i(x) = 0$. -/
noncomputable def g (n : ℕ) (i : Fin (w n)) (x : ZMod (q n)) : ℝ :=
  if (x.cast : ZMod (p n i)) = (r_K n i : ZMod (p n i))
    ∨ (x.cast : ZMod (p n i)) = -(r_K n i : ZMod (p n i))
  then 1 else 0

/-- Define the global additive hit counter c(x)
Define the global additive hit counter
$c : \mathbb{Z}/q\mathbb{Z} \to \mathbb{R}$ as the sum of all local hits:
$$ c(x) = \sum_{i=1}^w g_i(x) $$ -/
noncomputable def c (n : ℕ) (x : ZMod (q n)) : ℝ :=
  ∑ i : Fin (w n), g n i x

/-- Define the total weighted mass of the interval S_1(n, W)
Define the total weighted mass of the interval $S_1(n, W)$:
$$ S_1(n, W) = \sum_{x \in \mathcal{A}_n} W(x) $$ -/
noncomputable def S_1 (n : ℕ) (W : ZMod (q n) → ℝ) : ℝ :=
  ∑ x ∈ A_n n, W (x : ZMod (q n))

/-- Define the weighted hit count S_2(n, W)
Define the weighted hit count $S_2(n, W)$:
$$ S_2(n, W) = \sum_{x \in \mathcal{A}_n} W(x) c(x) $$ -/
noncomputable def S_2 (n : ℕ) (W : ZMod (q n) → ℝ) : ℝ :=
  ∑ x ∈ A_n n, W (x : ZMod (q n)) * c n (x : ZMod (q n))

end

end KrafftSieve
